import DevicesWithFilterLayout from '@/layouts/DevicesWithFilterLayout';
import Mobile1 from '../../../../public/images/home/thumb_777314_phone_front_x_small.jpg';
import Mobile2 from '../../../../public/images/home/thumb_850151_phone_front_x_small.jpg';
import Mobile3 from '../../../../public/images/home/thumb_864704_phone_front_x_small.jpg';
const data = [
  {
    img: Mobile1,
    name: 'vivo iQOO Neo 8',
    country: 'China',
    rating: '4.0',
    reviewsNumber: '5K',
    detail: 'China - 12GB · 256GB',
    priceBefore: 449,
    priceAfter: 294,
  },
  {
    img: Mobile2,
    name: 'Oppo Find X7',
    country: 'USA',
    rating: '4.3',
    reviewsNumber: '3.2K',
    detail: 'China - 12GB · 256GB',
    priceBefore: 863,
    priceAfter: 396,
  },
  {
    img: Mobile3,
    name: 'Oppo Reno11',
    country: 'China',
    rating: '5.0',
    reviewsNumber: '5k',
    detail: 'China - 8GB · 256GB',
    priceBefore: 485,
    priceAfter: 400,
  },
  {
    img: Mobile1,
    name: 'vivo iQOO Neo 8',
    country: 'Global',
    rating: '4.6',
    reviewsNumber: '6k',
    detail: '12GB · 256GB',
    priceBefore: 449,
    priceAfter: 294,
  },
  {
    img: Mobile2,
    name: 'Oppo Find X7',
    country: 'Global',
    rating: '4.8',
    reviewsNumber: '529',
    detail: 'China - 12GB · 256GB',
    priceBefore: 863,
    priceAfter: 396,
  },
  {
    img: Mobile3,
    name: 'Oppo Reno11',
    country: 'China',
    rating: '4.5',
    reviewsNumber: '2k',
    detail: 'China - 8GB · 256GB',
    priceBefore: 485,
    priceAfter: 400,
  },
  {
    img: Mobile1,
    name: 'vivo iQOO Neo 8',
    country: 'Global',
    rating: '5.0',
    reviewsNumber: '532',
    detail: 'China - 12GB · 256GB',
    priceBefore: 449,
    priceAfter: 294,
  },
  {
    img: Mobile2,
    name: 'Oppo Find X7',
    country: 'China',
    rating: '3.0',
    reviewsNumber: '3k',
    detail: 'China - 12GB · 256GB',
    priceBefore: 863,
    priceAfter: 396,
  },
  {
    img: Mobile3,
    name: 'Oppo Reno11',
    country: 'India',
    rating: '4.3',
    reviewsNumber: '2.3k',
    detail: 'China - 8GB · 256GB',
    priceBefore: 485,
    priceAfter: 400,
  },
  {
    img: Mobile1,
    name: 'vivo iQOO Neo 8',
    country: 'China',
    rating: '4.0',
    reviewsNumber: '5K',
    detail: 'China - 12GB · 256GB',
    priceBefore: 449,
    priceAfter: 294,
  },
  {
    img: Mobile2,
    name: 'Oppo Find X7',
    country: 'USA',
    rating: '4.3',
    reviewsNumber: '3.2K',
    detail: 'China - 12GB · 256GB',
    priceBefore: 863,
    priceAfter: 396,
  },
  {
    img: Mobile3,
    name: 'Oppo Reno11',
    country: 'China',
    rating: '5.0',
    reviewsNumber: '5k',
    detail: 'China - 8GB · 256GB',
    priceBefore: 485,
    priceAfter: 400,
  },
  {
    img: Mobile1,
    name: 'vivo iQOO Neo 8',
    country: 'Global',
    rating: '4.6',
    reviewsNumber: '6k',
    detail: '12GB · 256GB',
    priceBefore: 449,
    priceAfter: 294,
  },
  {
    img: Mobile2,
    name: 'Oppo Find X7',
    country: 'Global',
    rating: '4.8',
    reviewsNumber: '529',
    detail: 'China - 12GB · 256GB',
    priceBefore: 863,
    priceAfter: 396,
  },
  {
    img: Mobile3,
    name: 'Oppo Reno11',
    country: 'China',
    rating: '4.5',
    reviewsNumber: '2k',
    detail: 'China - 8GB · 256GB',
    priceBefore: 485,
    priceAfter: 400,
  },
  {
    img: Mobile1,
    name: 'vivo iQOO Neo 8',
    country: 'Global',
    rating: '5.0',
    reviewsNumber: '532',
    detail: 'China - 12GB · 256GB',
    priceBefore: 449,
    priceAfter: 294,
  },
  {
    img: Mobile2,
    name: 'Oppo Find X7',
    country: 'China',
    rating: '3.0',
    reviewsNumber: '3k',
    detail: 'China - 12GB · 256GB',
    priceBefore: 863,
    priceAfter: 396,
  },
  {
    img: Mobile3,
    name: 'Oppo Reno11',
    country: 'India',
    rating: '4.3',
    reviewsNumber: '2.3k',
    detail: 'China - 8GB · 256GB',
    priceBefore: 485,
    priceAfter: 400,
  },
];

const SmartPhones = () => {
  return <DevicesWithFilterLayout devices={data} />;
};

export default SmartPhones;
