import ManagedModal from '@/components/UI/Modal/ManagedModal';
import { ModalProvider } from '@/components/UI/Modal/Modal.context';
import HeaderPage from '@/layouts/Header/HeaderPage';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider>
          <HeaderPage />
          {children}
          <ManagedModal />
        </ModalProvider>
      </body>
    </html>
  );
}
